<?php
use App\Helper;
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Poke 3000</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito+Sans&display=swap">
    <link rel="stylesheet" href="<?php echo Helper::asset('/css/app.css'); ?>">
</head>
<body>
<div id="app">
</div>
<script src="<?php echo Helper::asset('/js/app.js'); ?>"></script>
<script src="https://kit.fontawesome.com/f688d35c35.js" crossorigin="anonymous"></script>
</body>
</html>